services:
  - type: web
    name: wagtail-miniproject
    env: python
    plan: free
    buildCommand: |
      pip install -r requirements.txt
      python manage.py collectstatic --noinput --settings=mysite.settings.production
    startCommand: gunicorn mysite.wsgi:application
    autoDeploy: true
    envVars:
      - key: DEBUG
        value: "False"
      - key: SECRET_KEY
        generateValue: true
      - key: DATABASE_URL
        fromDatabase:
          name: wagtail-db
          property: connectionString
      - key: DJANGO_SETTINGS_MODULE
        value: mysite.settings.production

databases:
  - name: wagtail-db
    plan: free
